
package com.github.codingob.web.service.myservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://service.service.web.codingob.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://service.service.web.codingob.github.com/", className = "com.github.codingob.web.service.myservice.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.service.web.codingob.github.com/", className = "com.github.codingob.web.service.myservice.GetDataResponse")
    @Action(input = "http://service.service.web.codingob.github.com/MyService/getDataRequest", output = "http://service.service.web.codingob.github.com/MyService/getDataResponse")
    public String getData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
