version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=server
      - NGINX_PORT=80

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  redis:
    image: redis
    ports:
      - '6379:6379'

  mongodb:
    image: mongo
    ports:
      - '27017:27017'

  postgreSQL:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'